branch-defaults:
  default:
    environment: Udacity-Project-Backend-Prod
    group_suffix: null
deploy:
  artifact: Archive.zip
environment-defaults:
  Udacity-Project-Backend-Prod:
    branch: null
    repository: null
global:
  application_name: Udacity-Project
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
