orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install the front-end dependencies
          command: npm run frontend:install
      - run:
          name: Install the back-end dependencies
          command: npm run backend:install
      - run:
          name: Build the front-end project
          command: npm run frontend:build
      - run:
          name: Build the back-end project
          command: npm run backend:build
      - run:
          name: Deploy the front-end project
          command: npm run frontend:deploy
      - run:
          name: Deploy the back-end project
          command: npm run backend:deploy
